include: ../analysis_options.yaml

linter:
  rules:
    # DO reference all public properties in debug method implementations.
    #
    # https://dart.dev/tools/linter-rules/diagnostic_describe_all_properties.html
    #
    # Consider using this lint rule if you are making a public Flutter package.
    # For private ones and private apps we recommend keeping it off as you probably
    # won't be making diagnostic properties for all your
    # classes, unless you are using a data class lib that does it for you via code generation.
    #
    # Other known linters use:
    #
    # Core           false : https://pub.dev/packages/lints
    # Recommended    false : https://pub.dev/packages/lints
    # Flutter Lints  false : https://pub.dev/packages/flutter_lints
    # Flutter repo   false : https://github.com/flutter/flutter/blob/master/analysis_options_common.yaml
    # Lint           false : https://pub.dev/packages/lint
    # VG Analysis    false : https://pub.dev/packages/very_good_analysis
    # Riverpod/Remi  false : https://github.com/rrousselGit/riverpod/blob/master/analysis_options.yaml
    # 
    # We use this for packages but turn it OFF/false in apps.
    diagnostic_describe_all_properties: false

    # DO document all public members.
    #
    # https://dart.dev/tools/linter-rules/public_member_api_docs.html
    #
    # All non-overriding public members should be documented with /// doc-style comments.
    # Not necessary for an app, but nice to do when useful. We try to but do not enforce it.
    # If you write public packages keep this rule ON.
    #
    # Other known linters use:
    #
    # Core           false : https://pub.dev/packages/lints
    # Recommended    false : https://pub.dev/packages/lints
    # Flutter Lints  false : https://pub.dev/packages/flutter_lints
    # Flutter repo   false : https://github.com/flutter/flutter/blob/master/analysis_options_common.yaml
    # Lint           false : https://pub.dev/packages/lint
    # VG Analysis    true  : https://pub.dev/packages/very_good_analysis
    # Riverpod/Remi  true  : https://github.com/rrousselGit/riverpod/blob/master/analysis_options.yaml
    # 
    # We use this for packages but turn it OFF/false in apps.
    public_member_api_docs: false