name: flex_seed_scheme_example
description: Example that demonstrates how to use the FlexSeedScheme package.
version: 5.0.1
publish_to: 'none'
environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: '>=3.47.0'

dependencies:
  # Add Cupertino Icons font to your application. Used by the
  # CupertinoIcons class for iOS style icons, by Google flutter.dev.
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.9

  # The official Flutter Cupertino Design Library.
  cupertino_ui: ^1.0.0

  # Color picker package, by Mike Rydstrom, rydmike.com (@rydmike).
  # Used for color selection in the Playground to make customized color schemes.
  # https://pub.dev/packages/flex_color_picker
  flex_color_picker: ^4.0.0

  # FlexSeedScheme package, by Mike Rydstrom, rydmike.com (@rydmike).
  # https://pub.dev/packages/flex_seed_scheme
  flex_seed_scheme:
    path: ../

  # The Flutter SDK library itself.
  flutter:
    sdk: flutter

  # The official Flutter Material UI Library.
  material_ui: ^1.0.0

  # Used for launching a WEB URL, by Google flutter.dev.
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  flex_seed_scheme:
    path: ../
