name: flex_seed_scheme
description: A more flexible and powerful version of Flutter's ColorScheme.fromSeed. Use multiple seed colors, custom chroma and tone mapping.
version: 3.4.1
homepage: https://github.com/rydmike/flex_seed_scheme
repository: https://github.com/rydmike/flex_seed_scheme
issue_tracker: https://github.com/rydmike/flex_seed_scheme/issues
documentation: https://github.com/rydmike/flex_seed_scheme/blob/master/README.md
screenshots:
  - description: 'Using 1 seed colors to make M3 ColorScheme with candy pop strategy'
    path: example/screenshots/candy_pop_light_1.png
  - description: 'Using 4 seed colors to make M3 ColorScheme with candy pop strategy'
    path: example/screenshots/candy_pop_light_4.png
  - description: 'Using 4 seed colors to make M3 ColorScheme with custom seed strategy'
    path: example/screenshots/custom_light_4.png
  - description: 'Example of light mode widgets with the custom seed strategy'
    path: example/screenshots/custom_light_4_widgets.png
  - description: 'Example of light mode widgets with the candy pop seed strategy'
    path: example/screenshots/candy_pop_light_4_widgets.png
  - description: 'Example of dark mode widgets with the custom seed strategy'
    path: example/screenshots/custom_dark_4_widgets.png
  - description: 'Example of dark mode widgets with the candy pop seed strategy'
    path: example/screenshots/candy_pop_dark_4_widgets.png
topics:
  - theme
  - colorscheme
  - material3
  - color
  - materialdesign

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  # Used by mcu: tonal_palette.dart, require at least 1.18.0.
  # https://pub.dev/packages/collection
  collection: ^1.18.0

  flutter:
    sdk: flutter

  # Annotations used to express developer intentions that can't otherwise be deduced by
  # statically analyzing source code. Package is from Google dart.dev team.
  #
  # Flutter does not expose the "@internal" annotation via foundation, to use it we need to import the package.
  # Version 1.9.1 is first with updated SDK constraints to >=2.12.0 <4.0.0.
  # https://pub.dev/packages/meta
  meta: ^1.9.1

dev_dependencies:

  flutter_test:
    sdk: flutter
  # Used by color_matcher.dart in tests.
  matcher: ^0.12.16+1
  test:
