name: flex_seed_scheme
description: A more flexible and powerful version of Flutter's ColorScheme.fromSeed. Use multiple seed colors, custom chroma and tone mapping.
version: 1.3.0
homepage: https://github.com/rydmike/flex_seed_scheme
repository: https://github.com/rydmike/flex_seed_scheme
issue_tracker: https://github.com/rydmike/flex_seed_scheme/issues
documentation: https://github.com/rydmike/flex_seed_scheme/blob/master/README.md
screenshots:
  - description: 'Using 3 seed colors to make an M3 ColorScheme with M3 default chroma'
    path: example/screenshots/three_seeds_with_m3_chroma.png
  - description: 'Using 3 seed colors to make an M3 ColorScheme with custom chroma limits and tone mapping'
    path: example/screenshots/three_seeds_with_custom_chroma_and_tones.png
  - description: 'Using 3 seed colors to make a high-contrast M3 ColorScheme'
    path: example/screenshots/dark_three_seeds_high_contrast.png
  - description: 'Using 3 seed colors to make an ultra high-contrast M3 ColorScheme'
    path: example/screenshots/dark_three_seeds_ultra_high_contrast.png

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  # Used by mcu: tonal_palette.dart
  # Require at least 1.15.0, the first stable version for null-safety.
  collection: ^1.15.0

  flutter:
    sdk: flutter

  # Annotations used to express developer intentions that can't otherwise be deduced by
  # statically analyzing source code. Package is from Google dart.dev team.
  #
  # Flutter does not expose the "@internal" annotation via foundation, to use it we need to
  # import the package.
  meta: ^1.8.0

dev_dependencies:

  flutter_test:
    sdk: flutter
  # used by color_matcher.dart
  matcher: ^0.12.0
  test:
